"""Declarative schemas for public, synthetic, and simulated operational tables."""

from __future__ import annotations

from typing import Any

Status = str  # PASS | WARN | FAIL

IBM_TELCO_SCHEMA: dict[str, Any] = {
    "name": "ibm_telco",
    "required_columns": [
        "customerID",
        "gender",
        "SeniorCitizen",
        "Partner",
        "Dependents",
        "tenure",
        "PhoneService",
        "MultipleLines",
        "InternetService",
        "OnlineSecurity",
        "OnlineBackup",
        "DeviceProtection",
        "TechSupport",
        "StreamingTV",
        "StreamingMovies",
        "Contract",
        "PaperlessBilling",
        "PaymentMethod",
        "MonthlyCharges",
        "TotalCharges",
        "Churn",
    ],
    "id_column": "customerID",
    "target_column": "Churn",
    "target_positive": "Yes",
    "dtypes": {
        "customerID": "string",
        "gender": "string",
        "SeniorCitizen": "integer",
        "Partner": "string",
        "Dependents": "string",
        "tenure": "integer",
        "PhoneService": "string",
        "MultipleLines": "string",
        "InternetService": "string",
        "OnlineSecurity": "string",
        "OnlineBackup": "string",
        "DeviceProtection": "string",
        "TechSupport": "string",
        "StreamingTV": "string",
        "StreamingMovies": "string",
        "Contract": "string",
        "PaperlessBilling": "string",
        "PaymentMethod": "string",
        "MonthlyCharges": "float",
        "TotalCharges": "numeric_or_blank",
        "Churn": "string",
    },
    "allowed_values": {
        "gender": ["Female", "Male"],
        "SeniorCitizen": [0, 1],
        "Partner": ["Yes", "No"],
        "Dependents": ["Yes", "No"],
        "PhoneService": ["Yes", "No"],
        "MultipleLines": ["Yes", "No", "No phone service"],
        "InternetService": ["DSL", "Fiber optic", "No"],
        "OnlineSecurity": ["Yes", "No", "No internet service"],
        "OnlineBackup": ["Yes", "No", "No internet service"],
        "DeviceProtection": ["Yes", "No", "No internet service"],
        "TechSupport": ["Yes", "No", "No internet service"],
        "StreamingTV": ["Yes", "No", "No internet service"],
        "StreamingMovies": ["Yes", "No", "No internet service"],
        "Contract": ["Month-to-month", "One year", "Two year"],
        "PaperlessBilling": ["Yes", "No"],
        "PaymentMethod": [
            "Electronic check",
            "Mailed check",
            "Bank transfer (automatic)",
            "Credit card (automatic)",
        ],
        "Churn": ["Yes", "No"],
    },
    "numeric_ranges": {
        "tenure": {"min": 0, "max": 72},
        "MonthlyCharges": {"min": 0, "max": 200},
        "SeniorCitizen": {"min": 0, "max": 1},
    },
}

SYNTHETIC_OPERATIONAL_SCHEMA: dict[str, Any] = {
    "name": "synthetic_operational",
    "required_columns": [
        "customer_id",
        "age",
        "tenure_months",
        "contract_type",
        "payment_method",
        "monthly_charges",
        "total_charges",
        "data_usage_gb",
        "voice_usage_minutes",
        "support_calls",
        "complaints",
        "late_payments",
        "discount_percent",
        "last_login_days",
        "churn",
    ],
    "id_column": "customer_id",
    "target_column": "churn",
    "target_positive": 1,
    "dtypes": {
        "customer_id": "string",
        "age": "integer",
        "tenure_months": "integer",
        "contract_type": "string",
        "payment_method": "string",
        "monthly_charges": "float",
        "total_charges": "float",
        "data_usage_gb": "float",
        "voice_usage_minutes": "float",
        "support_calls": "integer",
        "complaints": "integer",
        "late_payments": "integer",
        "discount_percent": "float",
        "last_login_days": "integer",
        "churn": "integer",
    },
    "allowed_values": {
        "contract_type": ["Month-to-month", "One year", "Two year"],
        "payment_method": [
            "Electronic check",
            "Mailed check",
            "Bank transfer (automatic)",
            "Credit card (automatic)",
        ],
        "complaints": [0, 1],
        "churn": [0, 1],
    },
    "numeric_ranges": {
        "age": {"min": 18, "max": 80},
        "tenure_months": {"min": 0, "max": 72},
        "monthly_charges": {"min": 0, "max": 200},
        "total_charges": {"min": 0, "max": 20000},
        "data_usage_gb": {"min": 0, "max": 100},
        "voice_usage_minutes": {"min": 0, "max": 3000},
        "support_calls": {"min": 0, "max": 30},
        "late_payments": {"min": 0, "max": 24},
        "discount_percent": {"min": 0, "max": 100},
        "last_login_days": {"min": 0, "max": 90},
    },
}

IRANIAN_CHURN_SCHEMA: dict[str, Any] = {
    "name": "uci_iranian_churn",
    "required_columns": [
        "Call Failure",
        "Complains",
        "Subscription Length",
        "Charge Amount",
        "Seconds of Use",
        "Frequency of use",
        "Frequency of SMS",
        "Distinct Called Numbers",
        "Age Group",
        "Tariff Plan",
        "Status",
        "Customer Value",
        "Churn",
    ],
    "id_column": None,
    "target_column": "Churn",
    "target_positive": 1,
    "dtypes": {
        "Call Failure": "integer",
        "Complains": "integer",
        "Subscription Length": "integer",
        "Charge Amount": "integer",
        "Seconds of Use": "integer",
        "Frequency of use": "integer",
        "Frequency of SMS": "integer",
        "Distinct Called Numbers": "integer",
        "Age Group": "integer",
        "Tariff Plan": "integer",
        "Status": "integer",
        "Customer Value": "float",
        "Churn": "integer",
    },
    "allowed_values": {
        "Complains": [0, 1],
        "Tariff Plan": [1, 2],
        "Status": [1, 2],
        "Churn": [0, 1],
        "Age Group": [1, 2, 3, 4, 5],
    },
    "numeric_ranges": {
        "Call Failure": {"min": 0, "max": 50},
        "Subscription Length": {"min": 0, "max": 120},
        "Charge Amount": {"min": 0, "max": 9},
        "Seconds of Use": {"min": 0, "max": 200000},
        "Customer Value": {"min": 0, "max": 3000},
    },
}

SCHEMAS = {
    "ibm_telco": IBM_TELCO_SCHEMA,
    "synthetic_operational": SYNTHETIC_OPERATIONAL_SCHEMA,
    "uci_iranian_churn": IRANIAN_CHURN_SCHEMA,
}


def get_schema(name: str) -> dict[str, Any]:
    """Return a named schema or raise KeyError."""
    if name not in SCHEMAS:
        raise KeyError(f"Unknown schema '{name}'. Known: {sorted(SCHEMAS)}")
    return SCHEMAS[name]
